backend:
  name: git-gateway
  branch: main

# For local development - uncomment this
# local_backend: true

media_folder: "public/images"
public_folder: "/images"

# https://decapcms.org/docs/widgets/
collections:
  - name: "gallery"
    label: "Photo Gallery Images"
    folder: "src/content/gallery"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - {label: "Image", name: "image", widget: "image", hint: "Upload the image file for the gallery. Recommended dimensions: 1200x630px"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime", hint: "This is the date that will be used to sort your images in the gallery. It does not have to be the date the photo was taken."}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Caption", name: "caption", widget: "string", required: false}
  - name: "blog"
    label: "News & Updates"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false, hint: "This is a large image that appears at the beginning of your article. Recommended dimensions: 1200x630px"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Image Gallery"
        name: "imageGallery"
        widget: "object"
        required: false
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Description", name: "description", widget: "text", required: false}
          - label: "Images"
            name: "gallery"
            widget: "list"
            required: false
            hint: "Add additional images to your article. These will appear below the main content. Recommended dimensions: 640x480px"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Caption", name: "caption", widget: "string", required: false}
  - name: "faqs"
    label: "Frequently Asked Questions"
    folder: "src/content/faqs"
    create: true
    slug: "{{question}}"
    fields:
      - {label: "Question", name: "question", widget: "string"}
      - {label: "Sort Priority", name: "sortPriority", widget: "number", required: false, hint: "Determines the order of the FAQs. Lower numbers (like 0 or 1) appear first."}
      - {label: "Body", name: "body", widget: "markdown"}